name: CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build test --scan

      - name: Request Jitpack Build
        run: |
          COMMIT_ID=$(git rev-parse HEAD | cut -c1-10)
          curl -s -m 30 https://jitpack.io/com/github/Zxilly/upgrader/$COMMIT_ID/build.log
